version: "3"

services:
  redis:
    image: "redis"
    container_name: "redis"
    hostname: "redis"
    network_mode: bridge
    expose: 
      - "6379"
    ports:
      - "6379:6379"

  mysql:
    image: "mysql"
    container_name: "mysql"
    restart: "always"
    command: --default-authentication-plugin=mysql_native_password
    network_mode: bridge
    volumes:
      - "./database/simple_crud_db.sql:/docker-entrypoint-initdb.d/simple_crud_db.sql:ro"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "simple_crud_db"
    expose:
      - "3306"
    ports:
    - "3306:3306"
  
  run-login:
    container_name: login
    image: "login"
    network_mode: bridge
    depends_on:
      - "redis"
      - "mysql"
    links:
      - "redis"
      - "mysql"
    environment:
      APP_HOST: "PROD"
      APP_PORT: "8881"
      DB: "mysql"
      DB_HOST: "host.docker.internal"
      DB_NAME: "simple_crud_db"
      DB_PORT: "3306"
      DB_USER: "root"
      DB_PASS: ""
      BCR_ROUND: "12"
      REDIS_PORT: "6379"
      REDIS_HOST: ""
    ports:
      - "8881:8881"
    restart: "always"

  run-users:
    container_name: users
    image: "users"
    network_mode: bridge
    depends_on:
      - "run-login"
      - "mysql"
    links:
      - "run-login"
      - "mysql"
    environment:
      APP_HOST: "DEV"
      APP_PORT: "8882"
      DB: "mysql"
      DB_HOST: "host.docker.internal"
      DB_NAME: "simple_crud_db"
      DB_PORT: "3306"
      DB_USER: "root"
      DB_PASS: ""
      LOGIN_URL: "http://login:8881/"
      BCR_ROUND: "12"
    ports:
      - "8882:8882"
    restart: "always"